# Generated by Django 3.0.11 on 2021-04-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTransferData',
            fields=[
                ('locationtransferid', models.AutoField(db_column='LocationTransferID', primary_key=True, serialize=False)),
                ('locationtransferstatus', models.CharField(blank=True, db_column='LocationTransferStatus', max_length=10, null=True)),
                ('registertimestamp', models.DateTimeField(blank=True, db_column='RegisterTimestamp', null=True)),
                ('statustimestamp', models.DateTimeField(blank=True, db_column='StatusTimestamp', null=True)),
            ],
            options={
                'db_table': 'LOCATION_TRANSFER_DATA',
                'managed': False,
            },
        ),
    ]
