# Generated by Django 3.0.11 on 2021-04-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_locationtransferdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeData',
        ),
    ]
