# Generated by Django 3.0.11 on 2021-04-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_locationtransferdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentstage', models.SmallIntegerField(blank=True, db_column='CurrentStage', null=True)),
                ('ison', models.BooleanField(blank=True, db_column='IsOn', null=True)),
            ],
            options={
                'db_table': 'USER_DATA',
                'managed': False,
            },
        ),
    ]
