# Generated by Django 3.0.11 on 2021-04-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_userdata'),
        ('db', '0003_delete_employeedata'),
    ]

    operations = [
    ]
